package com.youtubestream.app.ui.theme

import androidx.compose.ui.graphics.Color

// D3 — a real brand color identity (a teal scheme), replacing the default Android-Studio purple.
// This is a hand-authored starting point; the canonical workflow is to regenerate from a seed with
// Material Theme Builder (https://m3.material.io/theme-builder) and paste its Color.kt export over this.

// --- Light ---
val primaryLight = Color(0xFF006A60)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFF74F8E5)
val onPrimaryContainerLight = Color(0xFF00201C)
val secondaryLight = Color(0xFF4A635F)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFCCE8E2)
val onSecondaryContainerLight = Color(0xFF05201C)
val tertiaryLight = Color(0xFF446273)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCBE6FF)
val onTertiaryContainerLight = Color(0xFF001E2E)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFAFDFB)
val onBackgroundLight = Color(0xFF191C1B)
val surfaceLight = Color(0xFFF7FAF8)
val onSurfaceLight = Color(0xFF191C1B)
val surfaceVariantLight = Color(0xFFDAE5E1)
val onSurfaceVariantLight = Color(0xFF3F4946)
val outlineLight = Color(0xFF6F7975)
val outlineVariantLight = Color(0xFFBEC9C4)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF2D312F)
val inverseOnSurfaceLight = Color(0xFFEFF1EE)
val inversePrimaryLight = Color(0xFF53DBC9)
val surfaceDimLight = Color(0xFFD8DBD8)
val surfaceBrightLight = Color(0xFFF7FAF8)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF0F4F1)
val surfaceContainerLight = Color(0xFFEAEFEC)
val surfaceContainerHighLight = Color(0xFFE5EAE7)
val surfaceContainerHighestLight = Color(0xFFDFE4E1)

// --- Dark ---
val primaryDark = Color(0xFF53DBC9)
val onPrimaryDark = Color(0xFF003731)
val primaryContainerDark = Color(0xFF005048)
val onPrimaryContainerDark = Color(0xFF74F8E5)
val secondaryDark = Color(0xFFB1CCC6)
val onSecondaryDark = Color(0xFF1C3531)
val secondaryContainerDark = Color(0xFF324B47)
val onSecondaryContainerDark = Color(0xFFCCE8E2)
val tertiaryDark = Color(0xFFACCAE6)
val onTertiaryDark = Color(0xFF143349)
val tertiaryContainerDark = Color(0xFF2C4A60)
val onTertiaryContainerDark = Color(0xFFCBE6FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF101413)
val onBackgroundDark = Color(0xFFE0E3E0)
val surfaceDark = Color(0xFF101413)
val onSurfaceDark = Color(0xFFE0E3E0)
val surfaceVariantDark = Color(0xFF3F4946)
val onSurfaceVariantDark = Color(0xFFBEC9C4)
val outlineDark = Color(0xFF899390)
val outlineVariantDark = Color(0xFF3F4946)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE0E3E0)
val inverseOnSurfaceDark = Color(0xFF2D312F)
val inversePrimaryDark = Color(0xFF006A60)
val surfaceDimDark = Color(0xFF101413)
val surfaceBrightDark = Color(0xFF353A38)
val surfaceContainerLowestDark = Color(0xFF0B0F0E)
val surfaceContainerLowDark = Color(0xFF191C1B)
val surfaceContainerDark = Color(0xFF1D211F)
val surfaceContainerHighDark = Color(0xFF272B29)
val surfaceContainerHighestDark = Color(0xFF323634)
